### ISSUE TITLE
Control Dataset Proposals

### ISSUE THREAD

**Issue by atharva-tendle** [ManifoldRG/NEKO_Archive#4]
Goal:

We want to provide an initial subset of control environments, which can be used during the development process. This includes environments from this [sheet](https://docs.google.com/spreadsheets/d/18t38QKIMsZXiNxRcgDdKIxcrclPb5QEzvVKvGQBSJ98/edit#gid=0), or other potential alternatives. 

Some points regarding the chosen environments:

- We may want a set of envs that cover the different possible input/output (output: continuous vs discrete actions), (input: vector vs image observations), so we can test different tokenization methods
- Initially, we want environments that have fully already collected datasets. If a dataset is not available, but a well-performing released agent is available, with released weights, we could consider generating datasets. 
- We want environments that support the standard Gym(nasium) API, or have bindings (such as https://github.com/Farama-Foundation/Shimmy)  that perform this conversation (this should be most if not all environments). 

**Output:**

- Update the proposal tab in the sheet with the chosen datasets and their attributes
- Briefly discuss and justify choices

**Comment by daniellawson9999** [comment]
Updated description for the proposal

**Comment by harshsikka** [comment]
Great issue! It would be good to have the justification as some notes, maybe in an MD for anyone on our team to review.

**Comment by harshsikka** [comment]
@daniellawson9999 check out my comment here https://github.com/ManifoldRG/NEKO/issues/5#issuecomment-1552212054

**Comment by harshsikka** [comment]
Also realized, would be a good idea for us to contact the 2 different individuals/teams who have attempted GATO before, and understand the challenges they faced 😆

**Comment by daniellawson9999** [comment]
@harshsikka Yes, we should especially reach out to OrigamiDream. The other repo is essentially trying to convert their code to Pytorch, with most of their config files, etc, based on the first repo. Regarding what quantifies as a good dataset, I have been thinking the most towards dataset accessibility and infrastructure. In the following comment, I can my notes for the dataset recommendation.

**Comment by daniellawson9999** [comment]
# Preface

- As previsouly recommended, we want a minimal set of environments to use for initial development that captures a variety of different kinds of observation (input) and action (output) to test various Gato embedding schemes. Feel free to give feedback on this idea or let me know if things need more explanation or do not seem like a good choice. 

# Ideas

## Atari ALE environments
 - Classic RL benchmark, with image-based observation and discrete actions. 
 - Gato used data collected from Muesli
 - publicly available data is the DQN Replay Dataset containg episodes from 

Repos:
contain
https://github.com/deepmind/deepmind-research/tree/master/rl_unplugged or https://github.com/google-research/batch_rl

[D4RL-Atari](https://github.com/takuseno/d4rl-atari): Wrapper which makes it easier much to load data, in D4RL style format, or filter for higher quality data from last 1M timesteps within each environment (what we would want to train on).


## Continuous Control

To complement the high-dimensional image observations of Atari, a second set of environments that could be useful are robotics tasks such as the MuJoCo locomotion or Deepmind Control environments, which are both continuous control tasks with low-dimensional observations and actions.

Two options I would recommend to start with:

### Deepmind Control Datset (DMC):
[Rl Unplugged](https://github.com/deepmind/deepmind-research/tree/master/rl_unplugged) again provides data, but only for 7 tasks (According to Table 1, Gato had 30 tasks from DMControl) collected with D4PG and V-MPO for manipulator environments. A of this dataset is that there is some similarity to Gato, in that DMControl was also used, however our results would not be comparable, as we would need data over all 30 tasks, and they do not provide results for this specific subset we have. A disadvantage is that DMControl is generally not a popular benchmark for Offline RL, and this may not make it as useful for others in the community. This dataset is not being actively maintained, and also does not have a conveinent wrapper for loading data.

### D4RL
(D4RL repo)[https://github.com/Farama-Foundation/D4RL],(paper)[https://arxiv.org/abs/2004.07219] is the go-to benchmark for offline reinforcement learning research. Building off D4RL would provide advantages of it being actively maintained, and having easy interfaces for loading data. People working in offline RL research may find model pre-trained on many D4RL tasks to be useful for building off.  There are serveral datasets supported, where I would recommend we start with the simple locomotion datasets (halfcheetah, hopper, walker), which are similar to those in DMControl. Later, we could extend to further datasets, such as Adroit.


# Recommendation and Plan

For initial experimentation, use [D4RL](https://github.com/Farama-Foundation/D4RL) MuJoCo Locomotion + Atari ALE data from RL_Unplugged/Batch_RL but using the [D4RL Atari adapter](https://github.com/takuseno/d4rl-atari). While this recommendation is intended to be a good start for development, there is no available model that can play all/most atari games while performing robotics locomotion tasks, let alone adding in datasets from vision/language modalities.

Some advantages of this plan:
 -  Can compare progress to papers with existing results which have open implementations. For example, [Decision Transformer](https://arxiv.org/abs/2106.01345) trains individual models for specific MuJoCo or Atari tasks, but not one model to simultaneously do all tasks. [Multi-Game DT](https://arxiv.org/pdf/2205.15241.pdf) trains one model for ~41 Atari games, but not to also handle seperate MuJoCo tasks. 
 - If we need help w/ dataset infrastructure, D4RL fits within the gymnasium/farama infrastructure, can use tools like [Shimmy](https://github.com/Farama-Foundation/Shimmy) to wrap Atari-ALE environment to have some interface as the MuJoCo locomotion environments.  

 I have updated these two datasets in the sheet. A todo item is quantifiying numerically the gap between DNQ and Muesli on Atari dataset.

## Actions to implement plan
Some high-level steps that we can follow if sticking with the recommendation above:

1. Create centralized repo, try to set up dependencies to handle D4RL MuJoCo + Atari environment. Likely use the D4RL Atari adapter repo for dataset, but may have to replace their adapter with the one from Shimmy. The output of this task would be a single file (supported by others) that can jointly load datasets and environments from D4RL MuJoCo and Atari, with both the datasets and the environment in the same unified format.
2. At this point, the data could be used for testing. For example, test Gato model to just do one locomotion task, or just learn to play 1 game, then have model play 1 game + 1 locomot task, then many tasks + many games. 
3. At the point of training on many games + many robotics environmnets, we will need more infrastucture. For example, we cannot just simply load all data in memory as used by default in D4RL. However, while working or thinking about this step (3), we can use the progress of step 2 to test if we can properly train a model / work on architecture. 

- At step 2/3, look into [Minari](https://minari.farama.org/main/content/basic_usage/), https://github.com/Farama-Foundation/Minari, currently in beta but could use, and add our own datasets, or copy how they store datasets in HD5F format and only load in single episodes at a time to avoid memory issues.

**Comment by harshsikka** [comment]
@daniellawson9999 great work. I think this sounds reasonable. I had a chance to look at all the dataset/environment/availability combinations and corresponding notes you kept in the [tracking sheet](https://docs.google.com/spreadsheets/d/18t38QKIMsZXiNxRcgDdKIxcrclPb5QEzvVKvGQBSJ98/edit#gid=0). 

I write the below just to share with the team how I'm considering your notes, so we can all stay on the same page. 

Truthfully there are a lot of ways we could go about selecting a combination of datasets to start with. We're simultaneously considering:

- what data is available 
- what datasets/objective makes for a meaningful combination of tasks
- "meaningful" can mean interesting from a research perspective, interesting due to 0 data transferability, etc

I'm less familiar with Robotics and Control Research, so a lot of these datasets are newish to me. I can see several combinations that seem interesting (the babyAI objective in particular sounds interesting because of the language component). 

What I really like is the observation you're making around the novelty of the two tasks, and the lack of public model or research combining atari + robot locomotion, coupled with data availability. 

So I think we have a path forward for our first couple control datasets. Now we need a few vision/language ones.

**Comment by daniellawson9999** [comment]
I agree that BabyAI would be a great environment to explore sometime. I think this could be one of the better environments to experiment with the intersection of language + decision-making. 

The original [babyai repo](https://github.com/mila-iqia/babyai), is now being maintained under Farama as well as [Minigrid](https://github.com/Farama-Foundation/Minigrid). In the 2023 update of the babyai repo, it discusses this change and also says:

"This repository still contains scripts which, if adapted to the Minigrid library, could be used to:
- Produce demonstrations using the [BabyAI bot](babyai/bot.py),
- [Train Imitation Learning agents](babyai/imitation.py) using the bot-generated demonstrations as training trajectories."

I am not sure if someone has completed this adaptation yet, and also sourced a publicly available dataset, but I could not find it. Due to these reasons, I thought it may be easier to first prioritize working with the environments that already have available/standardized datasets.  


This is slightly not related, but I recently saw this paper which has an interesting approach that is evaluated using minigrid : [Think Before You Act: Unified Policy for Interleaving
Language Reasoning with Actions](https://arxiv.org/pdf/2304.11063.pdf). The paper trains a transformer policy which is conditioned on language instructions/observations, and predicts actions, both of which are standard. However, the transformer also predicts language sub-goals as it solves a task, interleaving chain-of-thought like text to help with reasoning. This is a recent workshop paper, so maybe they release their datasets in the future.

**Comment by harshsikka** [comment]
Excellent. Clearly, Farama is doing really good work, they're carrying the open source maintenance of so many things we are considering using. 

@daniellawson9999 I think summarizing some of these considerations for the group meeting later this week would be good, maybe as a slide or two (you can refer people to these notes). My hope is that we can have a good initial proposal on dataset/objective, and an understanding of an underlying architecture.

Given those two pieces, we can scope out what the first experimental aim is, and can put together a more concrete larger picture. 

And we can get to building :)

**Comment by daniellawson9999** [comment]
Sounds good @harshsikka . Here is one more point before the meeting on Sunday elaborating on ideas related to Minari. 

## Previous Proposal Recap

Previously, I recommended the combination of D4RL MuJoCo plus Atari ALE as a good starting point. There are some points in the previous comment, but I wanted to elaborate on another path and some additional ideas.

## Dataset Standards and D4RL
Generally, there has not been much of a unified standard for datasets in Offline RL. The closest thing to this was [D4RL](https://github.com/Farama-Foundation/D4RL), but is was essentially a set benchmark, rather than a dataset repository. While I had seen its development starting for Minari, a new API for datasets, right after releasing the proposal, they just released [first major announcement](Minari)[https://farama.org/Announcing-Minari]) which gave information that makes its use quite compelling. This aims to standardize using control datasets, and open-source the effort for collect RL datasets. Another useful attribute that has been lacking is a focus on efficiency / scalabilty. D4RL, and many other RL datasets store all data in one file One then loads this entire dataset into RAM, which would not scale beyond training more than a couple dataset. I was anticipating that we would have to take existing data and then convert it to a format that fixes this, but Minari now handles this. For example, individual trajectories/episodes can be accessed / loaded into memory individually:

```
import minari

dataset = minari.load_dataset("door-cloned-v0")
episodes_generator = dataset.iterate_episodes(episode_indices=[1, 2, 0])

for episode in episodes_generator:
    print(f"EPISODE ID {episode.id}")
```

I think the community will start to build / contribute to this project, and it may be the easiest way to crowdsource the control dataset process. I think in the long run, it is clear that it makes sense to use this, but I am curious about the best short-term decision. The MuJoCo D4RL dataset which I previously wanted to use is currently a priority item for being added, and I/we could contribute to this, and probably get it in. If they are interested in regenerating the dataset instead of just importing, to meet the new environment version or for other reproducibility reasons then this may take a little longer. While the D4RL MuJoCO dataset will soon be added, currently, I do not think they have planned to add Atari ALE, as they are first prioritizing environments/datasets they have been maintaining. However, they do state "Currently, we only provide a skeleton number of datasets, with a focus on porting over all D4RL datasets and soon the [CrowdPlay datasets](https://farama-foundation.github.io/CrowdPlay/)." The main CrowdPlay dataset is human demonstrations on Atari. If we want to use Minari, which I think could be beneficial, I think there are roughly two strategies:

 1) Fork Minari, port older D4RL and D4RL-Atari to Minari. Contrib to main if they are interested in these datasets. (They may be interested in regenerating D4RL and the crowdplay, so maybe not). By fork I mean sticking with their API/code-base, using dataset format, but not submitting datasets if they do not meet standards/current priotities. 
 2) Use available datasets in Minari (Adrot, Franka, PointMaze, soon to be regenerated all of D4RL including MuJoCo). For new datasets, help w/ contribs, or just use them as they are added. Prioritize using official datatsets or adding rather than our own fork.

I am reaching out to the lead working on Minari to see if they plan to regenerate, port old datasets, or both, and maybe get more info related to their plans to see how well things could line up. I haven't mentioned the general purpose (for Neko), just sent a message regarding their porting vs regeneration.
